spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mybatistest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    # type: com.alibaba.druid.pool.DruidDataSource
    hikari:
      auto-commit: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
      

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    use-generated-keys: true
    use-column-label:  true
    map-underscore-to-camel-case: true
    
 
  